[package]
name = "rust-bin-wasi"
version = "0.1.0"
authors = ["e1r0nd <a.merezhanyi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "*"
