[package]
name = "mdown-wasm"
version = "0.1.0"
authors = ["Anatol Merezhanyi <a.merezhanyi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pulldown-cmark = "*"
wasm-bindgen = "*"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false